import { Outfit } from "next/font/google";
import "./globals.css";
import TopBar from "@/_components/top.bar";
import { Provider } from "@/lib/provider";
import FeedLayout from "@/_components/feed.layout";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${outfit.variable} antialiased`}>
        <Provider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <TopBar />
          <FeedLayout>{children}</FeedLayout>
        </Provider>
      </body>
    </html>
  );
}
